baseURL = 'https://forlaiyin.github.io/'
title = 'LYY的笔记站'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
theme = 'book'

[languages]
  [languages.zh]
    languageName = '中文'
    weight = 1
    contentDir = 'content.zh'

[params]
  description = '莱茵好！希望今天莱茵也开心，这是一个LYY搭的静态网站，用来存放一些笔记'
  BookTheme = 'auto'  # auto, dark, light
  BookSearch = true
  BookMenuBundle = '/menu'
  BookToC = true
  BookPortableLinks = true
  BookComments = false
  BookEditPath = 'https://github.com/lyy-66/forlaiyin.github.io/edit/main/exampleSite'
